image:
  registry: k8s.gcr.io
  repository: external-dns/external-dns
  tag: v0.11.0
  pullPolicy: IfNotPresent

priorityClassName: system-cluster-critical

policy: sync
provider: cloudflare

cloudflare:
  proxied: true